// Nomi di icone lucide-react renderizzate dal sito. Il componente
// components/home/icon-map.ts mappa il nome al componente icona, quindi questa
// lista deve restare allineata con quella mappa.
export const iconOptions = [
  "check",
  "clock",
  "zap",
  "layers",
  "monitor",
  "shield",
  "award",
  "activity",
  "graduation-cap",
  "file-text",
  "credit-card",
  "volume-2",
  "users",
  "heart-pulse",
  "baby",
  "sparkles",
  "smile",
  "crown",
  "syringe",
  "align-center",
  "scissors",
  "sun",
  "refresh-cw",
  "droplets",
  "wind",
];
