/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SeoImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "seoImage.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  youtubeUrl?: string;
  description?: string;
  publishedAt?: string;
  order?: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  authorName?: string;
  text?: string;
  rating?: number;
  date?: string;
  source?: "Google" | "Facebook" | "Diretta";
  featured?: boolean;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  items?: Array<
    {
      _key: string;
    } & NavItem
  >;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  shortName?: string;
  doctor?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  yearsBadge?: string;
  phone?: string;
  email?: string;
  whatsapp?: string;
  address?: {
    street?: string;
    postalCode?: string;
    city?: string;
    province?: string;
  };
  openingHours?: string;
  socials?: Array<{
    platform?: "Facebook" | "Instagram" | "YouTube" | "LinkedIn" | "TikTok";
    url?: string;
    _type: "social";
    _key: string;
  }>;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: SeoImage;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type ServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "service";
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type NavItem = {
  _type: "navItem";
  label?: string;
  linkType?: "path" | "internal" | "external";
  path?: string;
  internalLink?: PageReference | ServiceReference | PostReference;
  externalUrl?: string;
  openInNewTab?: boolean;
  children?: Array<
    {
      _key: string;
    } & NavLink
  >;
};

export type NavLink = {
  _type: "navLink";
  label?: string;
  linkType?: "path" | "internal" | "external";
  path?: string;
  internalLink?: PageReference | ServiceReference | PostReference;
  externalUrl?: string;
  openInNewTab?: boolean;
};

export type StaffMemberReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "staffMember";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  excerpt?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  author?: StaffMemberReference;
  body?: BlockContent;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: SeoImage;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type StaffMember = {
  _id: string;
  _type: "staffMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  role?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: BlockContent;
  order?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: BlockContent;
  order?: number;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: SeoImage;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  intro?: string;
  body?: BlockContent;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: SeoImage;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | SeoImage
  | Video
  | Testimonial
  | Navigation
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | PageReference
  | ServiceReference
  | PostReference
  | NavItem
  | NavLink
  | StaffMemberReference
  | Post
  | BlockContent
  | StaffMember
  | Slug
  | Service
  | Page
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../sanity/lib/queries.ts
// Variable: NAVIGATION_QUERY
// Query: *[_id == "navigation"][0]{    items[]{        _key,  label,  linkType,  path,  externalUrl,  openInNewTab,  internalLink->{ _type, "slug": slug.current },      children[]{   _key,  label,  linkType,  path,  externalUrl,  openInNewTab,  internalLink->{ _type, "slug": slug.current } }    }  }
export type NAVIGATION_QUERY_RESULT =
  | {
      items: null;
    }
  | {
      items: Array<{
        _key: string;
        label: string | null;
        linkType: "external" | "internal" | "path" | null;
        path: string | null;
        externalUrl: string | null;
        openInNewTab: boolean | null;
        internalLink:
          | {
              _type: "page";
              slug: string | null;
            }
          | {
              _type: "post";
              slug: string | null;
            }
          | {
              _type: "service";
              slug: string | null;
            }
          | null;
        children: Array<{
          _key: string;
          label: string | null;
          linkType: "external" | "internal" | "path" | null;
          path: string | null;
          externalUrl: string | null;
          openInNewTab: boolean | null;
          internalLink:
            | {
                _type: "page";
                slug: string | null;
              }
            | {
                _type: "post";
                slug: string | null;
              }
            | {
                _type: "service";
                slug: string | null;
              }
            | null;
        }> | null;
      }> | null;
    }
  | null;

// Source: ../sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{    siteName,    shortName,    doctor,    yearsBadge,    phone,    email,    whatsapp,    address,    openingHours,    socials[]{ _key, platform, url },    seoTitle,    seoDescription  }
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      siteName: null;
      shortName: null;
      doctor: null;
      yearsBadge: null;
      phone: null;
      email: null;
      whatsapp: null;
      address: null;
      openingHours: null;
      socials: null;
      seoTitle: null;
      seoDescription: null;
    }
  | {
      siteName: null;
      shortName: null;
      doctor: null;
      yearsBadge: null;
      phone: null;
      email: null;
      whatsapp: null;
      address: null;
      openingHours: null;
      socials: null;
      seoTitle: string | null;
      seoDescription: string | null;
    }
  | {
      siteName: string | null;
      shortName: string | null;
      doctor: string | null;
      yearsBadge: string | null;
      phone: string | null;
      email: string | null;
      whatsapp: string | null;
      address: {
        street?: string;
        postalCode?: string;
        city?: string;
        province?: string;
      } | null;
      openingHours: string | null;
      socials: Array<{
        _key: string;
        platform:
          "Facebook" | "Instagram" | "LinkedIn" | "TikTok" | "YouTube" | null;
        url: string | null;
      }> | null;
      seoTitle: string | null;
      seoDescription: string | null;
    }
  | null;

// Source: ../sanity/lib/queries.ts
// Variable: VIDEOS_QUERY
// Query: *[_type == "video"] | order(order asc, publishedAt desc){    _id,    title,    youtubeUrl,    description,    publishedAt  }
export type VIDEOS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  youtubeUrl: string | null;
  description: string | null;
  publishedAt: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "navigation"][0]{\n    items[]{\n      \n  _key,\n  label,\n  linkType,\n  path,\n  externalUrl,\n  openInNewTab,\n  internalLink->{ _type, "slug": slug.current }\n,\n      children[]{ \n  _key,\n  label,\n  linkType,\n  path,\n  externalUrl,\n  openInNewTab,\n  internalLink->{ _type, "slug": slug.current }\n }\n    }\n  }\n': NAVIGATION_QUERY_RESULT;
    '\n  *[_id == "siteSettings"][0]{\n    siteName,\n    shortName,\n    doctor,\n    yearsBadge,\n    phone,\n    email,\n    whatsapp,\n    address,\n    openingHours,\n    socials[]{ _key, platform, url },\n    seoTitle,\n    seoDescription\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "video"] | order(order asc, publishedAt desc){\n    _id,\n    title,\n    youtubeUrl,\n    description,\n    publishedAt\n  }\n': VIDEOS_QUERY_RESULT;
  }
}
