/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SeoImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  youtubeUrl?: string;
  description?: string;
  publishedAt?: string;
  order?: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  authorName?: string;
  text?: string;
  rating?: number;
  date?: string;
  source?: "Google" | "Facebook" | "Diretta";
  featured?: boolean;
};

export type ClinicalCase = {
  _id: string;
  _type: "clinicalCase";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  badge?: string;
  imageBefore?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  imageAfter?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  description?: string;
  order?: number;
  showInHome?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  items?: Array<
    {
      _key: string;
    } & NavItem
  >;
  footerLinks?: Array<
    {
      _key: string;
    } & NavLink
  >;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  shortName?: string;
  doctor?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  yearsBadge?: string;
  footerDescription?: string;
  legalName?: string;
  vatNumber?: string;
  shareCapital?: string;
  alboRegistration?: string;
  phone?: string;
  email?: string;
  whatsapp?: string;
  address?: {
    street?: string;
    postalCode?: string;
    city?: string;
    province?: string;
  };
  openingHours?: string;
  socials?: Array<{
    platform?: "Facebook" | "Instagram" | "YouTube" | "LinkedIn" | "TikTok";
    url?: string;
    _type: "social";
    _key: string;
  }>;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: SeoImage;
};

export type HomePageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "homePage";
};

export type PricePageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "pricePage";
};

export type StudioPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "studioPage";
};

export type CasesPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "casesPage";
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type ServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "service";
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type NavItem = {
  _type: "navItem";
  label?: string;
  linkType?: "path" | "internal" | "external";
  path?: string;
  internalLink?:
    | HomePageReference
    | PricePageReference
    | StudioPageReference
    | CasesPageReference
    | PageReference
    | ServiceReference
    | PostReference;
  externalUrl?: string;
  openInNewTab?: boolean;
  children?: Array<
    {
      _key: string;
    } & NavLink
  >;
};

export type NavLink = {
  _type: "navLink";
  label?: string;
  linkType?: "path" | "internal" | "external";
  path?: string;
  internalLink?:
    | HomePageReference
    | PricePageReference
    | StudioPageReference
    | CasesPageReference
    | PageReference
    | ServiceReference
    | PostReference;
  externalUrl?: string;
  openInNewTab?: boolean;
};

export type StaffMemberReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "staffMember";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  excerpt?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  author?: StaffMemberReference;
  body?: BlockContent;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: SeoImage;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type StaffMember = {
  _id: string;
  _type: "staffMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  role?: string;
  category?: "medico" | "staff";
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  excerpt?: string;
  bio?: BlockContent;
  order?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  icon?: IconString;
  excerpt?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: BlockContent;
  order?: number;
  showInFooter?: boolean;
  priceBadge?: string;
  priceMin?: number;
  priceMax?: number;
  priceNote?: string;
  priceFeatures?: Array<string>;
  popular?: boolean;
  showInHome?: boolean;
  homeTitle?: string;
  homeExcerpt?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: SeoImage;
};

export type IconString =
  | "check"
  | "clock"
  | "zap"
  | "layers"
  | "monitor"
  | "shield"
  | "award"
  | "activity"
  | "graduation-cap"
  | "file-text"
  | "credit-card"
  | "volume-2"
  | "users"
  | "heart-pulse";

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  intro?: string;
  body?: BlockContent;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: SeoImage;
};

export type CasesPage = {
  _id: string;
  _type: "casesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    eyebrow?: string;
    title?: string;
    description?: string;
  };
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: SeoImage;
};

export type StudioPage = {
  _id: string;
  _type: "studioPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    eyebrow?: string;
    title?: string;
    description?: string;
    highlights?: Array<string>;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    imageRole?: string;
  };
  profile?: {
    enabled?: boolean;
    eyebrow?: string;
    title?: string;
    cards?: Array<{
      icon?: IconString;
      title?: string;
      text?: string;
      _type: "iconCard";
      _key: string;
    }>;
  };
  team?: {
    enabled?: boolean;
    eyebrow?: string;
    title?: string;
    description?: string;
  };
  studio?: {
    enabled?: boolean;
    eyebrow?: string;
    title?: string;
    description?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    features?: Array<{
      icon?: IconString;
      title?: string;
      text?: string;
      _type: "iconCard";
      _key: string;
    }>;
  };
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: SeoImage;
};

export type PricePage = {
  _id: string;
  _type: "pricePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    eyebrow?: string;
    title?: string;
    description?: string;
  };
  factors?: {
    enabled?: boolean;
    eyebrow?: string;
    title?: string;
    items?: Array<{
      icon?: IconString;
      title?: string;
      text?: string;
      _type: "factor";
      _key: string;
    }>;
  };
  list?: {
    enabled?: boolean;
    eyebrow?: string;
    title?: string;
    description?: string;
  };
  cta?: {
    enabled?: boolean;
    eyebrow?: string;
    title?: string;
    description?: string;
    boxTitle?: string;
  };
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: SeoImage;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    enabled?: boolean;
    badge?: string;
    title?: string;
    titleHighlight?: string;
    titleSuffix?: string;
    description?: string;
    features?: Array<{
      label?: string;
      icon?: IconString;
      _type: "feature";
      _key: string;
    }>;
    ctaPrimaryLabel?: string;
    ctaSecondaryLabel?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    experienceCard?: {
      value?: string;
      label?: string;
      sublabel?: string;
    };
  };
  stats?: {
    enabled?: boolean;
    items?: Array<{
      value?: string;
      label?: string;
      _type: "stat";
      _key: string;
    }>;
  };
  treatments?: {
    enabled?: boolean;
    eyebrow?: string;
    title?: string;
    description?: string;
  };
  doctorProfile?: {
    enabled?: boolean;
    eyebrow?: string;
    title?: string;
    roleLabel?: string;
    paragraphs?: Array<string>;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    highlights?: Array<{
      title?: string;
      subtitle?: string;
      icon?: IconString;
      _type: "highlight";
      _key: string;
    }>;
    ctaLabel?: string;
    ctaHref?: string;
  };
  clinicalCases?: {
    enabled?: boolean;
    eyebrow?: string;
    title?: string;
    description?: string;
  };
  contact?: {
    enabled?: boolean;
    eyebrow?: string;
    title?: string;
    description?: string;
    formTitle?: string;
  };
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: SeoImage;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | SeoImage
  | Video
  | Testimonial
  | ClinicalCase
  | SanityImageCrop
  | SanityImageHotspot
  | Navigation
  | SiteSettings
  | HomePageReference
  | PricePageReference
  | StudioPageReference
  | CasesPageReference
  | PageReference
  | ServiceReference
  | PostReference
  | NavItem
  | NavLink
  | StaffMemberReference
  | Post
  | BlockContent
  | StaffMember
  | Slug
  | Service
  | IconString
  | Page
  | CasesPage
  | StudioPage
  | PricePage
  | HomePage
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../sanity/lib/queries.ts
// Variable: NAVIGATION_QUERY
// Query: *[_id == "navigation"][0]{    items[]{        _key,  label,  linkType,  path,  externalUrl,  openInNewTab,  internalLink->{ _type, "slug": slug.current },      children[]{   _key,  label,  linkType,  path,  externalUrl,  openInNewTab,  internalLink->{ _type, "slug": slug.current } }    },    footerLinks[]{   _key,  label,  linkType,  path,  externalUrl,  openInNewTab,  internalLink->{ _type, "slug": slug.current } }  }
export type NAVIGATION_QUERY_RESULT =
  | {
      items: null;
      footerLinks: null;
    }
  | {
      items: Array<{
        _key: string;
        label: string | null;
        linkType: "external" | "internal" | "path" | null;
        path: string | null;
        externalUrl: string | null;
        openInNewTab: boolean | null;
        internalLink:
          | {
              _type: "casesPage";
              slug: null;
            }
          | {
              _type: "homePage";
              slug: null;
            }
          | {
              _type: "page";
              slug: string | null;
            }
          | {
              _type: "post";
              slug: string | null;
            }
          | {
              _type: "pricePage";
              slug: null;
            }
          | {
              _type: "service";
              slug: string | null;
            }
          | {
              _type: "studioPage";
              slug: null;
            }
          | null;
        children: Array<{
          _key: string;
          label: string | null;
          linkType: "external" | "internal" | "path" | null;
          path: string | null;
          externalUrl: string | null;
          openInNewTab: boolean | null;
          internalLink:
            | {
                _type: "casesPage";
                slug: null;
              }
            | {
                _type: "homePage";
                slug: null;
              }
            | {
                _type: "page";
                slug: string | null;
              }
            | {
                _type: "post";
                slug: string | null;
              }
            | {
                _type: "pricePage";
                slug: null;
              }
            | {
                _type: "service";
                slug: string | null;
              }
            | {
                _type: "studioPage";
                slug: null;
              }
            | null;
        }> | null;
      }> | null;
      footerLinks: Array<{
        _key: string;
        label: string | null;
        linkType: "external" | "internal" | "path" | null;
        path: string | null;
        externalUrl: string | null;
        openInNewTab: boolean | null;
        internalLink:
          | {
              _type: "casesPage";
              slug: null;
            }
          | {
              _type: "homePage";
              slug: null;
            }
          | {
              _type: "page";
              slug: string | null;
            }
          | {
              _type: "post";
              slug: string | null;
            }
          | {
              _type: "pricePage";
              slug: null;
            }
          | {
              _type: "service";
              slug: string | null;
            }
          | {
              _type: "studioPage";
              slug: null;
            }
          | null;
      }> | null;
    }
  | null;

// Source: ../sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{    siteName,    shortName,    doctor,    logo,    yearsBadge,    footerDescription,    legalName,    vatNumber,    shareCapital,    alboRegistration,    phone,    email,    whatsapp,    address,    openingHours,    socials[]{ _key, platform, url },    seoTitle,    seoDescription,    seoImage  }
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      siteName: null;
      shortName: null;
      doctor: null;
      logo: null;
      yearsBadge: null;
      footerDescription: null;
      legalName: null;
      vatNumber: null;
      shareCapital: null;
      alboRegistration: null;
      phone: null;
      email: null;
      whatsapp: null;
      address: null;
      openingHours: null;
      socials: null;
      seoTitle: null;
      seoDescription: null;
      seoImage: null;
    }
  | {
      siteName: null;
      shortName: null;
      doctor: null;
      logo: null;
      yearsBadge: null;
      footerDescription: null;
      legalName: null;
      vatNumber: null;
      shareCapital: null;
      alboRegistration: null;
      phone: null;
      email: null;
      whatsapp: null;
      address: null;
      openingHours: null;
      socials: null;
      seoTitle: string | null;
      seoDescription: string | null;
      seoImage: SeoImage | null;
    }
  | {
      siteName: string | null;
      shortName: string | null;
      doctor: string | null;
      logo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      yearsBadge: string | null;
      footerDescription: string | null;
      legalName: string | null;
      vatNumber: string | null;
      shareCapital: string | null;
      alboRegistration: string | null;
      phone: string | null;
      email: string | null;
      whatsapp: string | null;
      address: {
        street?: string;
        postalCode?: string;
        city?: string;
        province?: string;
      } | null;
      openingHours: string | null;
      socials: Array<{
        _key: string;
        platform:
          "Facebook" | "Instagram" | "LinkedIn" | "TikTok" | "YouTube" | null;
        url: string | null;
      }> | null;
      seoTitle: string | null;
      seoDescription: string | null;
      seoImage: SeoImage | null;
    }
  | null;

// Source: ../sanity/lib/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0]{    hero{      enabled,      badge,      title,      titleHighlight,      titleSuffix,      description,      features[]{ _key, label, icon },      ctaPrimaryLabel,      ctaSecondaryLabel,      image{ ..., "alt": alt },      experienceCard    },    stats{      enabled,      items[]{ _key, value, label }    },    treatments{      enabled,      eyebrow,      title,      description    },    doctorProfile{      enabled,      eyebrow,      title,      roleLabel,      paragraphs,      image{ ..., "alt": alt },      highlights[]{ _key, title, subtitle, icon },      ctaLabel,      ctaHref    },    clinicalCases{      enabled,      eyebrow,      title,      description    },    contact{      enabled,      eyebrow,      title,      description,      formTitle    },    seoTitle,    seoDescription,    seoImage  }
export type HOME_PAGE_QUERY_RESULT =
  | {
      hero: null;
      stats: null;
      treatments: null;
      doctorProfile: null;
      clinicalCases: null;
      contact: null;
      seoTitle: null;
      seoDescription: null;
      seoImage: null;
    }
  | {
      hero: null;
      stats: null;
      treatments: null;
      doctorProfile: null;
      clinicalCases: null;
      contact: null;
      seoTitle: string | null;
      seoDescription: string | null;
      seoImage: SeoImage | null;
    }
  | {
      hero: {
        enabled: null;
        badge: null;
        title: string | null;
        titleHighlight: null;
        titleSuffix: null;
        description: string | null;
        features: null;
        ctaPrimaryLabel: null;
        ctaSecondaryLabel: null;
        image: null;
        experienceCard: null;
      } | null;
      stats: null;
      treatments: null;
      doctorProfile: null;
      clinicalCases: null;
      contact: null;
      seoTitle: string | null;
      seoDescription: string | null;
      seoImage: SeoImage | null;
    }
  | {
      hero: {
        enabled: null;
        badge: null;
        title: string | null;
        titleHighlight: null;
        titleSuffix: null;
        description: string | null;
        features: null;
        ctaPrimaryLabel: null;
        ctaSecondaryLabel: null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string | null;
          _type: "image";
        } | null;
        experienceCard: null;
      } | null;
      stats: null;
      treatments: null;
      doctorProfile: null;
      clinicalCases: null;
      contact: null;
      seoTitle: string | null;
      seoDescription: string | null;
      seoImage: SeoImage | null;
    }
  | {
      hero: {
        enabled: boolean | null;
        badge: string | null;
        title: string | null;
        titleHighlight: string | null;
        titleSuffix: string | null;
        description: string | null;
        features: Array<{
          _key: string;
          label: string | null;
          icon: IconString | null;
        }> | null;
        ctaPrimaryLabel: string | null;
        ctaSecondaryLabel: string | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string | null;
          _type: "image";
        } | null;
        experienceCard: {
          value?: string;
          label?: string;
          sublabel?: string;
        } | null;
      } | null;
      stats: {
        enabled: boolean | null;
        items: Array<{
          _key: string;
          value: string | null;
          label: string | null;
        }> | null;
      } | null;
      treatments: {
        enabled: boolean | null;
        eyebrow: string | null;
        title: string | null;
        description: string | null;
      } | null;
      doctorProfile: {
        enabled: boolean | null;
        eyebrow: string | null;
        title: string | null;
        roleLabel: string | null;
        paragraphs: Array<string> | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string | null;
          _type: "image";
        } | null;
        highlights: Array<{
          _key: string;
          title: string | null;
          subtitle: string | null;
          icon: IconString | null;
        }> | null;
        ctaLabel: string | null;
        ctaHref: string | null;
      } | null;
      clinicalCases: {
        enabled: boolean | null;
        eyebrow: string | null;
        title: string | null;
        description: string | null;
      } | null;
      contact: {
        enabled: boolean | null;
        eyebrow: string | null;
        title: string | null;
        description: string | null;
        formTitle: string | null;
      } | null;
      seoTitle: string | null;
      seoDescription: string | null;
      seoImage: SeoImage | null;
    }
  | null;

// Source: ../sanity/lib/queries.ts
// Variable: PRICE_PAGE_QUERY
// Query: *[_id == "pricePage"][0]{    hero{ eyebrow, title, description },    factors{      enabled,      eyebrow,      title,      items[]{ _key, icon, title, text }    },    list{ enabled, eyebrow, title, description },    cta{ enabled, eyebrow, title, description, boxTitle },    seoTitle,    seoDescription,    seoImage  }
export type PRICE_PAGE_QUERY_RESULT =
  | {
      hero: null;
      factors: null;
      list: null;
      cta: null;
      seoTitle: null;
      seoDescription: null;
      seoImage: null;
    }
  | {
      hero: null;
      factors: null;
      list: null;
      cta: null;
      seoTitle: string | null;
      seoDescription: string | null;
      seoImage: SeoImage | null;
    }
  | {
      hero: {
        eyebrow: null;
        title: string | null;
        description: string | null;
      } | null;
      factors: null;
      list: null;
      cta: null;
      seoTitle: string | null;
      seoDescription: string | null;
      seoImage: SeoImage | null;
    }
  | {
      hero: {
        eyebrow: string | null;
        title: string | null;
        description: string | null;
      } | null;
      factors: null;
      list: null;
      cta: null;
      seoTitle: string | null;
      seoDescription: string | null;
      seoImage: SeoImage | null;
    }
  | {
      hero: {
        eyebrow: string | null;
        title: string | null;
        description: string | null;
      } | null;
      factors: {
        enabled: boolean | null;
        eyebrow: string | null;
        title: string | null;
        items: Array<{
          _key: string;
          icon: IconString | null;
          title: string | null;
          text: string | null;
        }> | null;
      } | null;
      list: {
        enabled: boolean | null;
        eyebrow: string | null;
        title: string | null;
        description: string | null;
      } | null;
      cta: {
        enabled: boolean | null;
        eyebrow: string | null;
        title: string | null;
        description: string | null;
        boxTitle: string | null;
      } | null;
      seoTitle: string | null;
      seoDescription: string | null;
      seoImage: SeoImage | null;
    }
  | null;

// Source: ../sanity/lib/queries.ts
// Variable: HOME_SERVICES_QUERY
// Query: *[_type == "service" && showInHome == true] | order(order asc, title asc){    _id,    "slug": slug.current,    "title": coalesce(homeTitle, title),    "description": coalesce(homeExcerpt, excerpt),    icon  }
export type HOME_SERVICES_QUERY_RESULT = Array<{
  _id: string;
  slug: string | null;
  title: string | null;
  description: string | null;
  icon: IconString | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "service"] | order(order asc, title asc){    _id,    title,    "slug": slug.current,    excerpt,    icon,    image{ ..., "alt": alt }  }
export type SERVICES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  icon: IconString | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: FOOTER_SERVICES_QUERY
// Query: *[_type == "service" && showInFooter == true] | order(order asc, title asc){    _id,    title,    "slug": slug.current  }
export type FOOTER_SERVICES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: PRICED_SERVICES_QUERY
// Query: *[_type == "service" && defined(priceMin)] | order(order asc, title asc){    _id,    title,    "slug": slug.current,    excerpt,    priceBadge,    priceMin,    priceMax,    priceNote,    priceFeatures,    popular  }
export type PRICED_SERVICES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  priceBadge: string | null;
  priceMin: number;
  priceMax: number | null;
  priceNote: string | null;
  priceFeatures: Array<string> | null;
  popular: boolean | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: SERVICE_QUERY
// Query: *[_type == "service" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    excerpt,    icon,    image{ ..., "alt": alt },    body,    priceBadge,    priceMin,    priceMax,    priceNote,    seoTitle,    seoDescription,    seoImage  }
export type SERVICE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  icon: IconString | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
  body: BlockContent | null;
  priceBadge: string | null;
  priceMin: number | null;
  priceMax: number | null;
  priceNote: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  seoImage: SeoImage | null;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: SERVICE_SLUGS_QUERY
// Query: *[_type == "service" && defined(slug.current)]{ "slug": slug.current }
export type SERVICE_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: HOME_CASES_QUERY
// Query: *[_type == "clinicalCase" && showInHome == true] | order(order asc, title asc){    _id,    badge,    title,    description,    "image": imageAfter{ ..., "alt": alt }  }
export type HOME_CASES_QUERY_RESULT = Array<{
  _id: string;
  badge: string | null;
  title: string | null;
  description: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: CASES_QUERY
// Query: *[_type == "clinicalCase"] | order(order asc, title asc){    _id,    badge,    title,    description,    imageBefore{ ..., "alt": alt },    imageAfter{ ..., "alt": alt }  }
export type CASES_QUERY_RESULT = Array<{
  _id: string;
  badge: string | null;
  title: string | null;
  description: string | null;
  imageBefore: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
  imageAfter: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: CASES_PAGE_QUERY
// Query: *[_id == "casesPage"][0]{    hero{ eyebrow, title, description },    seoTitle,    seoDescription,    seoImage  }
export type CASES_PAGE_QUERY_RESULT =
  | {
      hero: null;
      seoTitle: null;
      seoDescription: null;
      seoImage: null;
    }
  | {
      hero: null;
      seoTitle: string | null;
      seoDescription: string | null;
      seoImage: SeoImage | null;
    }
  | {
      hero: {
        eyebrow: null;
        title: string | null;
        description: string | null;
      } | null;
      seoTitle: string | null;
      seoDescription: string | null;
      seoImage: SeoImage | null;
    }
  | {
      hero: {
        eyebrow: string | null;
        title: string | null;
        description: string | null;
      } | null;
      seoTitle: string | null;
      seoDescription: string | null;
      seoImage: SeoImage | null;
    }
  | null;

// Source: ../sanity/lib/queries.ts
// Variable: STUDIO_PAGE_QUERY
// Query: *[_id == "studioPage"][0]{    hero{      eyebrow,      title,      description,      highlights,      image{ ..., "alt": alt },      imageRole    },    profile{ enabled, eyebrow, title, cards[]{ _key, icon, title, text } },    team{ enabled, eyebrow, title, description },    studio{      enabled,      eyebrow,      title,      description,      image{ ..., "alt": alt },      features[]{ _key, icon, title, text }    },    seoTitle,    seoDescription,    seoImage  }
export type STUDIO_PAGE_QUERY_RESULT =
  | {
      hero: null;
      profile: null;
      team: null;
      studio: null;
      seoTitle: null;
      seoDescription: null;
      seoImage: null;
    }
  | {
      hero: null;
      profile: null;
      team: null;
      studio: null;
      seoTitle: string | null;
      seoDescription: string | null;
      seoImage: SeoImage | null;
    }
  | {
      hero: {
        eyebrow: null;
        title: string | null;
        description: string | null;
        highlights: null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string | null;
          _type: "image";
        } | null;
        imageRole: null;
      } | null;
      profile: null;
      team: null;
      studio: null;
      seoTitle: string | null;
      seoDescription: string | null;
      seoImage: SeoImage | null;
    }
  | {
      hero: {
        eyebrow: string | null;
        title: string | null;
        description: string | null;
        highlights: null;
        image: null;
        imageRole: null;
      } | null;
      profile: null;
      team: null;
      studio: null;
      seoTitle: string | null;
      seoDescription: string | null;
      seoImage: SeoImage | null;
    }
  | {
      hero: {
        eyebrow: string | null;
        title: string | null;
        description: string | null;
        highlights: Array<string> | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string | null;
          _type: "image";
        } | null;
        imageRole: string | null;
      } | null;
      profile: {
        enabled: boolean | null;
        eyebrow: string | null;
        title: string | null;
        cards: Array<{
          _key: string;
          icon: IconString | null;
          title: string | null;
          text: string | null;
        }> | null;
      } | null;
      team: {
        enabled: boolean | null;
        eyebrow: string | null;
        title: string | null;
        description: string | null;
      } | null;
      studio: {
        enabled: boolean | null;
        eyebrow: string | null;
        title: string | null;
        description: string | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string | null;
          _type: "image";
        } | null;
        features: Array<{
          _key: string;
          icon: IconString | null;
          title: string | null;
          text: string | null;
        }> | null;
      } | null;
      seoTitle: string | null;
      seoDescription: string | null;
      seoImage: SeoImage | null;
    }
  | null;

// Source: ../sanity/lib/queries.ts
// Variable: STAFF_QUERY
// Query: *[_type == "staffMember"] | order(order asc, name asc){    _id,    name,    role,    category,    excerpt,    photo{ ..., "alt": alt }  }
export type STAFF_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  role: string | null;
  category: "medico" | "staff" | null;
  excerpt: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc){    _id,    title,    "slug": slug.current,    publishedAt,    excerpt,    mainImage{ ..., "alt": alt },    "author": author->name  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  excerpt: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
  author: string | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    publishedAt,    excerpt,    mainImage{ ..., "alt": alt },    author->{ name, role, photo{ ..., "alt": alt } },    body,    seoTitle,    seoDescription,    seoImage  }
export type POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  excerpt: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
  author: {
    name: string | null;
    role: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string | null;
      _type: "image";
    } | null;
  } | null;
  body: BlockContent | null;
  seoTitle: string | null;
  seoDescription: string | null;
  seoImage: SeoImage | null;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{ "slug": slug.current }
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: VIDEOS_QUERY
// Query: *[_type == "video"] | order(order asc, publishedAt desc){    _id,    title,    youtubeUrl,    description,    publishedAt  }
export type VIDEOS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  youtubeUrl: string | null;
  description: string | null;
  publishedAt: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "navigation"][0]{\n    items[]{\n      \n  _key,\n  label,\n  linkType,\n  path,\n  externalUrl,\n  openInNewTab,\n  internalLink->{ _type, "slug": slug.current }\n,\n      children[]{ \n  _key,\n  label,\n  linkType,\n  path,\n  externalUrl,\n  openInNewTab,\n  internalLink->{ _type, "slug": slug.current }\n }\n    },\n    footerLinks[]{ \n  _key,\n  label,\n  linkType,\n  path,\n  externalUrl,\n  openInNewTab,\n  internalLink->{ _type, "slug": slug.current }\n }\n  }\n': NAVIGATION_QUERY_RESULT;
    '\n  *[_id == "siteSettings"][0]{\n    siteName,\n    shortName,\n    doctor,\n    logo,\n    yearsBadge,\n    footerDescription,\n    legalName,\n    vatNumber,\n    shareCapital,\n    alboRegistration,\n    phone,\n    email,\n    whatsapp,\n    address,\n    openingHours,\n    socials[]{ _key, platform, url },\n    seoTitle,\n    seoDescription,\n    seoImage\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_id == "homePage"][0]{\n    hero{\n      enabled,\n      badge,\n      title,\n      titleHighlight,\n      titleSuffix,\n      description,\n      features[]{ _key, label, icon },\n      ctaPrimaryLabel,\n      ctaSecondaryLabel,\n      image{ ..., "alt": alt },\n      experienceCard\n    },\n    stats{\n      enabled,\n      items[]{ _key, value, label }\n    },\n    treatments{\n      enabled,\n      eyebrow,\n      title,\n      description\n    },\n    doctorProfile{\n      enabled,\n      eyebrow,\n      title,\n      roleLabel,\n      paragraphs,\n      image{ ..., "alt": alt },\n      highlights[]{ _key, title, subtitle, icon },\n      ctaLabel,\n      ctaHref\n    },\n    clinicalCases{\n      enabled,\n      eyebrow,\n      title,\n      description\n    },\n    contact{\n      enabled,\n      eyebrow,\n      title,\n      description,\n      formTitle\n    },\n    seoTitle,\n    seoDescription,\n    seoImage\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_id == "pricePage"][0]{\n    hero{ eyebrow, title, description },\n    factors{\n      enabled,\n      eyebrow,\n      title,\n      items[]{ _key, icon, title, text }\n    },\n    list{ enabled, eyebrow, title, description },\n    cta{ enabled, eyebrow, title, description, boxTitle },\n    seoTitle,\n    seoDescription,\n    seoImage\n  }\n': PRICE_PAGE_QUERY_RESULT;
    '\n  *[_type == "service" && showInHome == true] | order(order asc, title asc){\n    _id,\n    "slug": slug.current,\n    "title": coalesce(homeTitle, title),\n    "description": coalesce(homeExcerpt, excerpt),\n    icon\n  }\n': HOME_SERVICES_QUERY_RESULT;
    '\n  *[_type == "service"] | order(order asc, title asc){\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    icon,\n    image{ ..., "alt": alt }\n  }\n': SERVICES_QUERY_RESULT;
    '\n  *[_type == "service" && showInFooter == true] | order(order asc, title asc){\n    _id,\n    title,\n    "slug": slug.current\n  }\n': FOOTER_SERVICES_QUERY_RESULT;
    '\n  *[_type == "service" && defined(priceMin)] | order(order asc, title asc){\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    priceBadge,\n    priceMin,\n    priceMax,\n    priceNote,\n    priceFeatures,\n    popular\n  }\n': PRICED_SERVICES_QUERY_RESULT;
    '\n  *[_type == "service" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    icon,\n    image{ ..., "alt": alt },\n    body,\n    priceBadge,\n    priceMin,\n    priceMax,\n    priceNote,\n    seoTitle,\n    seoDescription,\n    seoImage\n  }\n': SERVICE_QUERY_RESULT;
    '\n  *[_type == "service" && defined(slug.current)]{ "slug": slug.current }\n': SERVICE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "clinicalCase" && showInHome == true] | order(order asc, title asc){\n    _id,\n    badge,\n    title,\n    description,\n    "image": imageAfter{ ..., "alt": alt }\n  }\n': HOME_CASES_QUERY_RESULT;
    '\n  *[_type == "clinicalCase"] | order(order asc, title asc){\n    _id,\n    badge,\n    title,\n    description,\n    imageBefore{ ..., "alt": alt },\n    imageAfter{ ..., "alt": alt }\n  }\n': CASES_QUERY_RESULT;
    '\n  *[_id == "casesPage"][0]{\n    hero{ eyebrow, title, description },\n    seoTitle,\n    seoDescription,\n    seoImage\n  }\n': CASES_PAGE_QUERY_RESULT;
    '\n  *[_id == "studioPage"][0]{\n    hero{\n      eyebrow,\n      title,\n      description,\n      highlights,\n      image{ ..., "alt": alt },\n      imageRole\n    },\n    profile{ enabled, eyebrow, title, cards[]{ _key, icon, title, text } },\n    team{ enabled, eyebrow, title, description },\n    studio{\n      enabled,\n      eyebrow,\n      title,\n      description,\n      image{ ..., "alt": alt },\n      features[]{ _key, icon, title, text }\n    },\n    seoTitle,\n    seoDescription,\n    seoImage\n  }\n': STUDIO_PAGE_QUERY_RESULT;
    '\n  *[_type == "staffMember"] | order(order asc, name asc){\n    _id,\n    name,\n    role,\n    category,\n    excerpt,\n    photo{ ..., "alt": alt }\n  }\n': STAFF_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)] | order(publishedAt desc){\n    _id,\n    title,\n    "slug": slug.current,\n    publishedAt,\n    excerpt,\n    mainImage{ ..., "alt": alt },\n    "author": author->name\n  }\n': POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    publishedAt,\n    excerpt,\n    mainImage{ ..., "alt": alt },\n    author->{ name, role, photo{ ..., "alt": alt } },\n    body,\n    seoTitle,\n    seoDescription,\n    seoImage\n  }\n': POST_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)]{ "slug": slug.current }\n': POST_SLUGS_QUERY_RESULT;
    '\n  *[_type == "video"] | order(order asc, publishedAt desc){\n    _id,\n    title,\n    youtubeUrl,\n    description,\n    publishedAt\n  }\n': VIDEOS_QUERY_RESULT;
  }
}
