import {
  Check,
  Clock,
  Zap,
  Layers,
  Monitor,
  Shield,
  Award,
  Activity,
  GraduationCap,
  FileText,
  CreditCard,
  Volume2,
  Users,
  HeartPulse,
  Baby,
  Sparkles,
  Smile,
  Crown,
  Syringe,
  AlignCenter,
  Scissors,
  Sun,
  RefreshCw,
  Droplets,
  Wind,
  Calendar,
  Search,
  ClipboardList,
  Stethoscope,
  type LucideIcon,
} from "lucide-react";

// Mappa i nomi icona salvati in Sanity ai componenti lucide.
// Tenere allineata con iconOptions in studio/schemaTypes/shared/icons.ts.
const iconMap: Record<string, LucideIcon> = {
  check: Check,
  clock: Clock,
  zap: Zap,
  layers: Layers,
  monitor: Monitor,
  shield: Shield,
  award: Award,
  activity: Activity,
  "graduation-cap": GraduationCap,
  "file-text": FileText,
  "credit-card": CreditCard,
  "volume-2": Volume2,
  users: Users,
  "heart-pulse": HeartPulse,
  baby: Baby,
  sparkles: Sparkles,
  smile: Smile,
  crown: Crown,
  syringe: Syringe,
  "align-center": AlignCenter,
  scissors: Scissors,
  sun: Sun,
  "refresh-cw": RefreshCw,
  droplets: Droplets,
  wind: Wind,
  calendar: Calendar,
  search: Search,
  "clipboard-list": ClipboardList,
  stethoscope: Stethoscope,
};

export function resolveIcon(name: string | null | undefined, fallback: LucideIcon): LucideIcon {
  return (name && iconMap[name]) || fallback;
}
